version: '2'
services:
    spring-db:
        build: ./mysql
        environment:
            - MYSQL_DATABASE=spring
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=passw0rd
            - TZ=Japan
        ports:
            - "33069:3306"
